### ISSUE TITLE
admin启动报错

### ISSUE THREAD

**Issue by lijunyong** [Dromara/soul#103]
```

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.2.RELEASE)

2019-08-05 17:23:27.731  INFO 5944 --- [           main] o.d.soul.admin.SoulAdminApplication      : Starting SoulAdminApplication on server-1 with PID 5944 (D:\workspace-sts-3.8.4.RELEASE\soul\soul-admin\target\classes started by Administrator in D:\workspace-sts-3.8.4.RELEASE\soul\soul-admin)
2019-08-05 17:23:27.733 DEBUG 5944 --- [           main] o.d.soul.admin.SoulAdminApplication      : Running with Spring Boot v2.1.2.RELEASE, Spring v5.1.4.RELEASE
2019-08-05 17:23:27.734  INFO 5944 --- [           main] o.d.soul.admin.SoulAdminApplication      : The following profiles are active: local
2019-08-05 17:23:29.640  INFO 5944 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$c7c17d54] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-08-05 17:23:30.374  INFO 5944 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8887 (http)
2019-08-05 17:23:30.408  INFO 5944 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2019-08-05 17:23:30.408  INFO 5944 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.14]
2019-08-05 17:23:30.419  INFO 5944 --- [           main] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [C:\Java\jdk1.8.0_131\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Python\Python36\Scripts\;C:\Python\Python36\;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Java\jdk1.8.0_131\bin;C:\Program Files\Git\cmd;D:\apache-maven-3.3.9\bin;C:\gradle-4.2\bin;D:\go\bin;C:\Go\bin;C:\Users\Administrator\AppData\Local\Programs\Fiddler;C:\Users\Administrator\go\bin;.]
2019-08-05 17:23:30.653  INFO 5944 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2019-08-05 17:23:30.653  INFO 5944 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 2868 ms
2019-08-05 17:23:31.253  INFO 5944 --- [           main] o.d.s.a.s.init.LocalDataSourceLoader     : execute soul schema sql: META-INF/schema.sql
2019-08-05 17:23:31.828  INFO 5944 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : Inconsistent constructor declaration on bean with name 'appAuthController': single autowire-marked constructor flagged as optional - this constructor is effectively required since there is no default constructor to fall back to: public org.dromara.soul.admin.controller.AppAuthController(org.dromara.soul.admin.service.AppAuthService)
2019-08-05 17:23:31.832  INFO 5944 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : Inconsistent constructor declaration on bean with name 'appAuthService': single autowire-marked constructor flagged as optional - this constructor is effectively required since there is no default constructor to fall back to: public org.dromara.soul.admin.service.impl.AppAuthServiceImpl(org.dromara.soul.admin.mapper.AppAuthMapper,org.springframework.context.ApplicationEventPublisher)
2019-08-05 17:23:32.329  INFO 5944 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : Inconsistent constructor declaration on bean with name 'pluginService': single autowire-marked constructor flagged as optional - this constructor is effectively required since there is no default constructor to fall back to: public org.dromara.soul.admin.service.impl.PluginServiceImpl(org.dromara.soul.admin.mapper.PluginMapper,org.dromara.soul.admin.mapper.SelectorMapper,org.dromara.soul.admin.mapper.SelectorConditionMapper,org.dromara.soul.admin.mapper.RuleMapper,org.dromara.soul.admin.mapper.RuleConditionMapper,org.springframework.context.ApplicationEventPublisher)
2019-08-05 17:23:32.373  INFO 5944 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : Inconsistent constructor declaration on bean with name 'ruleService': single autowire-marked constructor flagged as optional - this constructor is effectively required since there is no default constructor to fall back to: public org.dromara.soul.admin.service.impl.RuleServiceImpl(org.dromara.soul.admin.mapper.RuleMapper,org.dromara.soul.admin.mapper.RuleConditionMapper,org.dromara.soul.admin.mapper.SelectorMapper,org.dromara.soul.admin.mapper.PluginMapper,org.springframework.context.ApplicationEventPublisher)
2019-08-05 17:23:32.384  INFO 5944 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : Inconsistent constructor declaration on bean with name 'selectorService': single autowire-marked constructor flagged as optional - this constructor is effectively required since there is no default constructor to fall back to: public org.dromara.soul.admin.service.impl.SelectorServiceImpl(org.dromara.soul.admin.mapper.SelectorMapper,org.dromara.soul.admin.mapper.SelectorConditionMapper,org.dromara.soul.admin.mapper.PluginMapper,org.dromara.soul.admin.mapper.RuleMapper,org.dromara.soul.admin.mapper.RuleConditionMapper,org.springframework.context.ApplicationEventPublisher)
2019-08-05 17:23:32.445  INFO 5944 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2019-08-05 17:23:32.464  INFO 5944 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2019-08-05 17:23:32.472 DEBUG 5944 --- [           main] o.d.s.a.mapper.AppAuthMapper.selectAll   : ==>  Preparing: select id, date_created, date_updated, app_key, app_secret, enabled from app_auth 
2019-08-05 17:23:32.501 DEBUG 5944 --- [           main] o.d.s.a.mapper.AppAuthMapper.selectAll   : ==> Parameters: 
2019-08-05 17:23:32.532 DEBUG 5944 --- [           main] o.d.s.a.mapper.AppAuthMapper.selectAll   : <==      Total: 0
2019-08-05 17:23:32.545 DEBUG 5944 --- [           main] o.d.s.a.mapper.PluginMapper.selectAll    : ==>  Preparing: select id, date_created, date_updated, name,config,role, enabled from plugin 
2019-08-05 17:23:32.546 DEBUG 5944 --- [           main] o.d.s.a.mapper.PluginMapper.selectAll    : ==> Parameters: 
2019-08-05 17:23:32.555 DEBUG 5944 --- [           main] o.d.s.a.mapper.PluginMapper.selectAll    : <==      Total: 8
2019-08-05 17:23:32.558  WARN 5944 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'configController': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.dromara.soul.admin.listener.http.HttpLongPollingDataChangedListener': Invocation of init method failed; nested exception is java.lang.ExceptionInInitializerError
2019-08-05 17:23:32.559  INFO 5944 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2019-08-05 17:23:32.563  INFO 5944 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2019-08-05 17:23:32.568  INFO 5944 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2019-08-05 17:23:32.584  INFO 5944 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-08-05 17:23:32.591 ERROR 5944 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'configController': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.dromara.soul.admin.listener.http.HttpLongPollingDataChangedListener': Invocation of init method failed; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:324) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1378) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:575) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.dromara.soul.admin.SoulAdminApplication.main(SoulAdminApplication.java:38) [classes/:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.dromara.soul.admin.listener.http.HttpLongPollingDataChangedListener': Invocation of init method failed; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1745) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1244) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1164) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:518) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:496) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:630) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:180) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:321) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	... 17 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
	at org.dromara.soul.admin.service.impl.PluginServiceImpl.listAll(PluginServiceImpl.java:222) ~[classes/:na]
	at org.dromara.soul.admin.service.impl.PluginServiceImpl$$FastClassBySpringCGLIB$$145ef7b3.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684) ~[spring-aop-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.dromara.soul.admin.service.impl.PluginServiceImpl$$EnhancerBySpringCGLIB$$f9a8b82d.listAll(<generated>) ~[classes/:na]
	at org.dromara.soul.admin.listener.AbstractDataChangedListener.updatePluginCache(AbstractDataChangedListener.java:215) ~[classes/:na]
	at org.dromara.soul.admin.listener.AbstractDataChangedListener.afterPropertiesSet(AbstractDataChangedListener.java:179) ~[classes/:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1741) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	... 32 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Cannot find implementation for org.dromara.soul.admin.transfer.PluginTransfer
	at org.mapstruct.factory.Mappers.getMapper(Mappers.java:79) ~[mapstruct-jdk8-1.2.0.Final.jar:na]
	at org.dromara.soul.admin.transfer.PluginTransfer.<clinit>(PluginTransfer.java:39) ~[classes/:na]
	... 41 common frames omitted
Caused by: java.lang.ClassNotFoundException: Cannot find implementation for org.dromara.soul.admin.transfer.PluginTransfer
	at org.mapstruct.factory.Mappers.getMapper(Mappers.java:93) ~[mapstruct-jdk8-1.2.0.Final.jar:na]
	at org.mapstruct.factory.Mappers.getMapper(Mappers.java:76) ~[mapstruct-jdk8-1.2.0.Final.jar:na]
	... 42 common frames omitted

```

**Comment by yu199195** [comment]
使用我提供的包》？

**Comment by lijunyong** [comment]
直接clone下来的代码

**Comment by yu199195** [comment]
这明显是少包，能否自己去解决下你的maven情况？

**Comment by lijunyong** [comment]
![image](https://user-images.githubusercontent.com/14291793/62520541-64dbac00-b860-11e9-9829-3c103ee32eb4.png)
我clone下来的代码，没报少包的错误

**Comment by yu199195** [comment]
install 以后，看下admin 源码下，有没生成实现类，设置jdk1.8
