### ISSUE TITLE
Duplicate handler name: write_timeout

### ISSUE THREAD

**Issue by naah69** [dromara/soul#1209]
## Describe the bug

multi request the same springcloud api.it error.

## Environment

- Soul version(s): 2.3.0

## Steps to reproduce

multi request the same springcloud api.it error.

## Debug logs

<details>
<summary>Click to expand</summary>

```
2021-03-29 19:57:19.752 WARN  [reactor-http-nio-4] io.netty.util.concurrent.AbstractEventExecutor Line:166 - A task raised an exception. Task: reactor.netty.resources.PooledConnectionProvider$DisposableAcquire@7125a6be
java.lang.IllegalArgumentException: Duplicate handler name: write_timeout
	at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:1055)
	at io.netty.channel.DefaultChannelPipeline.filterName(DefaultChannelPipeline.java:284)
	at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:160)
	at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:152)
	at org.dromara.soul.springboot.starter.plugin.httpclient.HttpClientPluginConfiguration.lambda$null$3(HttpClientPluginConfiguration.java:114)
	at reactor.netty.tcp.TcpClientDoOn.onStateChange(TcpClientDoOn.java:66)
	at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:518)
	at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.run(PooledConnectionProvider.java:633)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-03-29 19:57:21.109 WARN  [reactor-http-nio-4] reactor.netty.http.client.HttpClientConnect Line:299 - [id: 0xb690b44e, L:/192.168.102.4:62133 - R:/10.42.1.168:8080] The connection observed an error
io.netty.handler.timeout.ReadTimeoutException: null
2021-03-29 19:57:21.117 ERROR [reactor-http-nio-4] org.dromara.soul.plugin.httpclient.WebClientPlugin Line:120 - null
2021-03-29 19:57:21.120 ERROR [reactor-http-nio-4] org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler Line:122 - [8e94d41e-24]  500 Server Error for HTTP GET "/seed/v1/api/open/time"
```
</details>

**Comment by naah69** [comment]
yes, i will pr
