### ISSUE TITLE
An exception occurred when using soul-admin version 2.3.0

### ISSUE THREAD

**Issue by huangcanhui2018** [dromara/soul#1239]
## Describe the bug
An exception occurred after submitting the request for selector maintenance of the plug-in using the plug-in management function.The specific exception thrown is: 

```
Caused by: java.lang.ExceptionInInitializerError: null
	at org.dromara.soul.admin.service.impl.SelectorServiceImpl.publishEvent(SelectorServiceImpl.java:260)
	at org.dromara.soul.admin.service.impl.SelectorServiceImpl.createOrUpdate(SelectorServiceImpl.java:145)
	at org.dromara.soul.admin.service.impl.SelectorServiceImpl$$FastClassBySpringCGLIB$$3dce3747.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.transaction.interceptor.TransactionInterceptor$$Lambda$667/16532673.proceedWithInvocation(Unknown Source)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at org.dromara.soul.admin.service.impl.SelectorServiceImpl$$EnhancerBySpringCGLIB$$8ef3d001.createOrUpdate(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionInterceptor$$Lambda$667/16532673.proceedWithInvocation(Unknown Source)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy124.createOrUpdate(Unknown Source)
	at org.dromara.soul.admin.controller.SelectorController.createSelector(SelectorController.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	... 61 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Cannot find implementation for org.dromara.soul.admin.transfer.ConditionTransfer
	at org.mapstruct.factory.Mappers.getMapper(Mappers.java:61)
	at org.dromara.soul.admin.transfer.ConditionTransfer.<clinit>(ConditionTransfer.java:41)
	... 100 common frames omitted
Caused by: java.lang.ClassNotFoundException: Cannot find implementation for org.dromara.soul.admin.transfer.ConditionTransfer
	at org.mapstruct.factory.Mappers.getMapper(Mappers.java:75)
	at org.mapstruct.factory.Mappers.getMapper(Mappers.java:58)
	... 101 common frames omitted
```

## Environment

- Soul version(s): [2.3.0]
- JDK: 1.8.202
- IDE: eclipse
- OS: Win7

Please help to analyze the problem. Is it the problem of local environment or version compatibility?

**Comment by dengliming** [comment]
Can you provide the steps to reproduce this issue? Include the form data you submitted.

**Comment by huangcanhui2018** [comment]
> Can you provide the steps to reproduce this issue? Including the form data you submitted.

![soul-admin-selector-error](https://user-images.githubusercontent.com/45359999/113986820-42ddcc80-9880-11eb-92b3-6bf7d6793c09.png)

Please refer to the attached screenshot for the submitted data. Please help to analyze the cause of the problem. An exception was thrown when the exception was executed:

`ConditionTransfer INSTANCE = Mappers.getMapper(ConditionTransfer.class);`

No instance class object could be dynamically retrieved.

Thanks!

**Comment by dengliming** [comment]
@huangcanhui2018 How do you run your admin? I tested it locally and it worked.

**Comment by huangcanhui2018** [comment]
> @huangcanhui2018 How do you run your admin? I tested it locally and it worked.

When I perform SoulAdminBootstrap, or when I perform soul-admin-bin-2.3.0-release on GitHub, I get this exception. @dengliming

**Comment by dengliming** [comment]
@huangcanhui2018 
It seems that eclipse don't support generating implementation classes at compile time. You can use `intellij idea` or follow this [https://mapstruct.org/faq/#Can-I-use-MapStruct-within-Eclipse](https://mapstruct.org/faq/#Can-I-use-MapStruct-within-Eclipse) to try again. 

The other way, you can download the [soul-admin-bin-2.3.0-release](https://github.com/dromara/soul/releases/download/2.3.0/soul-admin-bin-2.3.0-RELEASE.tar.gz) and run as follow.
`java -jar soul-admin.jar --spring.profiles.active=h2`

**Comment by huangcanhui2018** [comment]
> @huangcanhui2018
> It seems that eclipse don't support generating implementation classes at compile time. You can use `intellij idea` or follow this https://mapstruct.org/faq/#Can-I-use-MapStruct-within-Eclipse to try again.
> 
> The other way, you can download the [soul-admin-bin-2.3.0-release](https://github.com/dromara/soul/releases/download/2.3.0/soul-admin-bin-2.3.0-RELEASE.tar.gz) and run as follow.
> `java -jar soul-admin.jar --spring.profiles.active=h2`, BTW, I tested it locally and it worked.

I updated the version of Eclipse to 2021-3 and the problem was resolved when I installed the m2e-apt plugin.
Thanks! @dengliming
