### ISSUE TITLE
Flaky Test: org.dromara.soul.metrics.prometheus.collector.JmxScraperTest

### ISSUE THREAD

**Issue by dengliming** [dromara/soul#1251]
This test fails occasionally
```

[INFO] Running org.dromara.soul.metrics.prometheus.collector.JmxScraperTest
Error:  Tests run: 3, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 393.186 s <<< FAILURE! - in org.dromara.soul.metrics.prometheus.collector.JmxScraperTest
Error:  org.dromara.soul.metrics.prometheus.collector.JmxScraperTest.testJmxScraperWithNonEmptyJmxUrlThenReceivedByReceiverDefaultExport  Time elapsed: 131.086 s  <<< ERROR!
java.rmi.ConnectException: 
Connection refused to host: 10.1.1.166; nested exception is: 
	java.net.ConnectException: Connection timed out (Connection timed out)
	at org.dromara.soul.metrics.prometheus.collector.JmxScraperTest.testJmxScraperWithNonEmptyJmxUrlThenReceivedByReceiverDefaultExport(JmxScraperTest.java:187)
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
	at org.dromara.soul.metrics.prometheus.collector.JmxScraperTest.testJmxScraperWithNonEmptyJmxUrlThenReceivedByReceiverDefaultExport(JmxScraperTest.java:187)

Error:  org.dromara.soul.metrics.prometheus.collector.JmxScraperTest.testJmxScraperWithNonEmptyJmxUrl  Time elapsed: 131.05 s  <<< ERROR!
java.rmi.ConnectException: 
Connection refused to host: 10.1.1.166; nested exception is: 
	java.net.ConnectException: Connection timed out (Connection timed out)
	at org.dromara.soul.metrics.prometheus.collector.JmxScraperTest.testJmxScraperWithNonEmptyJmxUrl(JmxScraperTest.java:140)
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
	at org.dromara.soul.metrics.prometheus.collector.JmxScraperTest.testJmxScraperWithNonEmptyJmxUrl(JmxScraperTest.java:140)
```

you can see full log detail
 [https://github.com/dromara/soul/runs/2312656102?check_suite_focus=true](https://github.com/dromara/soul/runs/2312656102?check_suite_focus=true)

[https://github.com/dromara/soul/pull/1225/checks?check_run_id=2310595614](https://github.com/dromara/soul/pull/1225/checks?check_run_id=2310595614)

**Comment by zhaiweij** [comment]
I'm willing to accept the task

**Comment by yu199195** [comment]
good luck to you！

**Comment by yu199195** [comment]
can not test it , i will close it
