### ISSUE TITLE
springcloud plugin miss serviceId

### ISSUE THREAD

**Issue by PandaUncle** [dromara/soul#1297]
## Describe the bug
i use springcloud plugin handle request, my service register rule to soul-admin, rule has the serviceId, then restart my service,  the rule serviceId is missed.  

## Environment

- Soul version(s): 2.3.0
- use nacos as register center

## Steps to reproduce
1、start soul-admin
2、start my service
3、check the rule has the serviceId
5、request can be handled correctly
6、restart my service
7、check the rule，serviceId is missed
8、request can not be handled and get error message response

```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ org.dromara.soul.web.configuration.ErrorHandlerConfiguration$1 [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.dromara.soul.web.filter.WebSocketParamFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.dromara.soul.web.filter.FileSizeFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.dromara.soul.bootstrap.filter.HealthFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.dromara.soul.web.filter.CrossFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ HTTP GET "/springcloud/order/findById?id=1" [ExceptionHandlingWebHandler]
Stack trace:
		at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
		at com.google.gson.Gson.fromJson(Gson.java:887)
		at com.google.gson.Gson.fromJson(Gson.java:852)
		at com.google.gson.Gson.fromJson(Gson.java:801)
		at com.google.gson.Gson.fromJson(Gson.java:773)
		at org.dromara.soul.common.utils.GsonUtils.fromJson(GsonUtils.java:110)
		at org.dromara.soul.plugin.springcloud.SpringCloudPlugin.doExecute(SpringCloudPlugin.java:72)
		at org.dromara.soul.plugin.base.AbstractSoulPlugin.execute(AbstractSoulPlugin.java:95)
		at org.dromara.soul.web.handler.SoulWebHandler$DefaultSoulPluginChain.lambda$execute$0(SoulWebHandler.java:100)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4105)
		at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:124)
		at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
		at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
```

## Expected behavior

No Exception.

**Comment by leohou0430** [comment]
did springcloud plugin status is open  in soul-admin?

**Comment by PandaUncle** [comment]
> did springcloud plugin status is open in soul-admin?

yes, i am sure.
I found that other people also found this bug。he submitted the issue on gitee.
https://gitee.com/dromara/soul/issues/I3HW1F

**Comment by dengliming** [comment]
Thanks for reporting this issue. I'll take a look at that.
