### ISSUE TITLE
soul-admin启不来，报端口被占用，怎么回事？

### ISSUE THREAD

**Issue by jinshubao** [Dromara/soul#15]
已经确认端口未被占用，启动时报端口被占用的错误

### 配置
```
server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://172.27.35.2:3306/soul?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&failOverReadOnly=false&autoReconnect=true
    username: root
    password: 123456
    dbcp2:
      driver-class-name: com.mysql.jdbc.Driver
  zookeeper:
    url : 172.27.35.2:2181
    sessionTimeout: 5000
    connectionTimeout : 2000
    serializer : KryoSerializer

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mappers/*.xml

logging:
  level:
    root: info
    org.springframework.boot: info
    org.apache.ibatis: info
    org.dromara.soul.bonuspoint: info
    org.dromara.soul.lottery: debug
    org.dromara.soul: debug

  path: "./logs/admin"
```
### 报错
```
2018-11-29 20:31:06.819 DEBUG 71276 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : Application failed to start due to an exception

org.springframework.boot.web.server.PortInUseException: Port 8086 is already in use
	at org.springframework.boot.web.embedded.netty.NettyWebServer.start(NettyWebServer.java:73) ~[spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext$ServerManager.start(ReactiveWebServerApplicationContext.java:232) ~[spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.startReactiveWebServer(ReactiveWebServerApplicationContext.java:130) ~[spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.finishRefresh(ReactiveWebServerApplicationContext.java:122) ~[spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:67) ~[spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.dromara.soul.admin.SoulAdminApplication.main(SoulAdminApplication.java:43) [classes/:na]

2018-11-29 20:31:06.819 ERROR 71276 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Web server failed to start. Port 8086 was already in use.

Action:

Identify and stop the process that's listening on port 8086 or configure this application to listen on another port.
```

**Comment by yu199195** [comment]
那应该是占用了，你本地机器重启下吧

**Comment by chinashelll** [comment]
8086是influxdb默认端口，项目换个端口启动
