### ISSUE TITLE
soul对dubbo方法单参数默认构建DefaultGenericParamResolveServiceImpl，不支持基本类型，列表及复杂javabean类型

### ISSUE THREAD

**Issue by springMonton** [Dromara/soul#175]
如下问题是基于soul-master代码分支发现的：
### 场景一
dubbo单参数，方法参数为Java基本类型，代码如下：
 @Override
    @SoulClient(path = "/findById", desc = "根据用户查询")
    public DubboTest findById(final String id) {
        DubboTest dubboTest = new DubboTest();
        dubboTest.setId(id);
        dubboTest.setName("hhah");
        return dubboTest;
    }

调用网关，http://localhost:9195/dubbo/findById        body设置:{"id":"1"}
response:
{
    "name": "hhah",
    "id": ""
}

阅读DefaultGenericParamResolveServiceImpl代码实现：
 @Override
    public Pair<String[], Object[]> buildParameter(final String body, final String parameterTypes) {
        final Map<String, Object> paramMap = GsonUtils.getInstance().toObjectMap(body);
        return new ImmutablePair<>(new String[]{parameterTypes}, new Object[]{paramMap});
    }

**按照dubbo泛化调用的标准，Pair中，left为参数类型，right为参数值。**但是代码中right直接设置的new Object[]{paramMap}，这个Object对象中是LinkedHashMap,"id"->"1"**（这样做有问题吧？？？）**

### 场景二
dubbo单参数，方法参数为List<Integer>，代码如下：
@Override
    @SoulClient(path = "/queryByArray2", desc = "插入一条数据")
    public String queryByArray2(Integer[] ids) {
        return "param array:" + ids;
    }

调用网关，http://localhost:9195/dubbo/queryByArray2
body设置:{
	"ids": [1, 2, 3]
}

soul-boostrap报错：io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: 
Caused by: java.lang.IllegalStateException: Serialized class com.google.gson.JsonArray must implement java.io.Serializable
	at com.alibaba.com.caucho.hessian.io.SerializerFactory.getDefaultSerializer(SerializerFactory.java:405)
	at com.alibaba.com.caucho.hessian.io.SerializerFactory.getSerializer(SerializerFactory.java:379)
	at com.alibaba.com.caucho.hessian.io.Hessian2Output.writeObject(Hessian2Output.java:389)
	at com.alibaba.com.caucho.hessian.io.MapSerializer.writeObject(MapSerializer.java:98)
	at com.alibaba.com.caucho.hessian.io.Hessian2Output.writeObject(Hessian2Output.java:391)
	at com.alibaba.com.caucho.hessian.io.BasicSerializer.writeObject(BasicSerializer.java:258)
	at com.alibaba.com.caucho.hessian.io.Hessian2Output.writeObject(Hessian2Output.java:391)
	at org.apache.dubbo.common.serialize.hessian2.Hessian2ObjectOutput.writeObject(Hessian2ObjectOutput.java:89)

**从异常信息看出Class序列化的时候报错了，那就debug确认一下soul构建出来的参数：
Pair中，代码中right直接设置的new Object[]{paramMap}，这个Object对象中是LinkedHashMap,内容：ids -> {JsonArray@11256}Collecting data…  （问题就在这个JsonArray）**

### 场景三
dubbo单参数，方法参数为javaBean（里面设置基本类型List），代码如下：
public class DubboTest implements Serializable {
    private String id;
    private String name;
   //加了一个列表
    private Integer[] ids;
}

dubbo服务定义：
@Override
    @SoulClient(path = "/insert", desc = "插入一条数据")
    public DubboTest insert(final DubboTest dubboTest) {
        // 模拟阻塞
        try {
            TimeUnit.SECONDS.sleep(8);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        return dubboTest;
    }

调用网关，http://localhost:9195/dubbo/insert
body设置:{
	"id": "1",
	"name": "1",
	"ids": [1, 2, 3]
}

soul-boostrap报错：io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: Serialized class com.google.gson.JsonArray must implement java.io.Serializable
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
	at io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:304)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
错误信息同上。同样排查方式发现Pair，right里面设置内容：
0 = {LinkedHashMap@11847}  size = 3
 "id" -> "1"
 "name" -> "1"
 "ids" -> {JsonArray@12246} "[1,2,3]"

分析上面的三种场景：
场景一：pair，right设置应该仅设置参数值paramMap.values().toArray(new Object[0])，不应该是new Object[]{paramMap}
场景二、三：同样问题，Gson序列化出来的数据跟我们预期的不符。试一下Jackson，应该能满足要求。

总结：针对dubbo单参数，正常理解应支持：基本类型，基本类型List、Map及javaBean设置（List<Object>、Map<Object>属性）等。上述问题是在阅读代码中发现的问题，望作者看到后能给予回复，如果是操作上面的问题还望提出来，谢谢！

**Comment by yu199195** [comment]
请仔细看文档，目前默认只支持无参数与javabean的参数

**Comment by springMonton** [comment]
> 请仔细看文档，目前默认只支持无参数与javabean的参数

你好，我这边读了最新的soul文档，原文中是这样描述的：

默认支持
默认实现类为: org.dromara.soul.web.plugin.dubbo.DefaultGenericParamResolveServiceImpl。
它只支持单个参数，包括基本类型，和javabean类型。
如果是javabean类型，它会把http body里面的json格式转成 Map类型，再通过泛化进行调用。

所以我理解为支持单参数基本类型。

回归话题，soul作为开源框架，dubbo单参数支持基本类型、基础类型List、Map及javaBean中支持（List<Object> fieldList, Map<Object> fieldMap）属性等，这些要求也是情理之中的。估计很多小伙伴也会有这样的诉求吧！

最近在阅读你的代码时，重点debug dubbo泛化调用这一块的逻辑，所以我这边针对soul dubbo单参数默认实现类DefaultGenericParamResolveServiceImpl，进行重新编码和补充测试。
目前dubbo方法单参数，已能支持:
基本类型

基本类型List、Map集合。
List<Integer> ids;
List<Long> ids;
List<String> names;
List<Double> widths;
...

Map<String, Integer> idMap;
Map<String, String> nameMap;
...

集合支持：
List<ComplexBeanTest> complexBeanTests  对象列表
...
Map<String, ComplexBeanTest> complexBeanTestMap  Map value为对象
...

javaBean中支持设置稍复杂属性：
@Data
public class ComplexBeanTest {

    private Integer[] idArrays;

    private List<String> idLists;

    private Map<String, Integer> idMaps;
}

 
如需要，我可以贡献代码和相应的测试用例。

**Comment by yu199195** [comment]
可以将你的代码，pr上来，我看看

**Comment by xautzh** [comment]
同求多参数支持代码

**Comment by springMonton** [comment]
> 可以将你的代码，pr上来，我看看

已经提交pull request了，麻烦你看一下，如有问题，请指正并一起讨论。

**Comment by springMonton** [comment]
> 可以将你的代码，pr上来，我看看

已提交pull request，麻烦你看一下，如有问题请指正并一起讨论，谢谢。

**Comment by springMonton** [comment]
> 同求多参数支持代码

这几天已经在看了，实现后会同步出来的。

**Comment by java-Learner-lx** [comment]
@springMonton 扩展，文档有大概介绍
