### ISSUE TITLE
EOFException异常相关

### ISSUE THREAD

**Issue by chyhub** [Dromara/soul#204]
请问下这个异常是不是不需要去处理它，每隔90秒断开连接就会报这个

2020-05-18 10:41:42.356 ERROR 5844 --- [0.0-9095-exec-8] o.d.s.a.l.websocket.WebsocketCollector   : websocket collection error:

java.io.EOFException: null
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1235) ~[tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1144) ~[tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:72) ~[tomcat-embed-websocket-9.0.29.jar:9.0.29]
	at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171) ~[tomcat-embed-websocket-9.0.29.jar:9.0.29]
	at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151) ~[tomcat-embed-websocket-9.0.29.jar:9.0.29]
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148) ~[tomcat-embed-websocket-9.0.29.jar:9.0.29]
	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54) ~[tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59) ~[tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860) ~[tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591) ~[tomcat-embed-core-9.0.29.jar:9.0.29]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.29.jar:9.0.29]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]

**Comment by yu199195** [comment]
请问为啥你的websocket会经常断开？

**Comment by chyhub** [comment]
> 请问为啥你的websocket会经常断开？

部署在DICE上面，admin这边每90秒就会断开一次，如果网关没问题，那可能是他们配置的问题

**Comment by chyhub** [comment]
> 请问为啥你的websocket会经常断开？

nginx配置了90秒不通信就断开连接，目前需要加心跳检测来处理这个断开问题

**Comment by yu199195** [comment]
> nginx配置了90秒不通信就断开连接，目前需要加心跳检测来处理这个断开问题

可以配置一下nginx的时间限制，或者主动加一下pingpong机制
