### ISSUE TITLE
文件上传问题

### ISSUE THREAD

**Issue by chyhub** [Dromara/soul#209]
refCnt: 0, decrement: 1 有木有遇到这个问题？

2020-05-20 14:26:14.232  WARN 15607 --- [r-http-kqueue-2] r.netty.http.client.HttpClientConnect    : [id: 0xe2d82fcc, L:/192.168.20.88:55598 - R:192.168.20.88/192.168.20.88:8186] The connection observed an error

io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[netty-codec-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.write(CombinedChannelDuplexHandler.java:348) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716) [netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:708) [netty-transport-4.1.43.Final.jar:4.1.43.Final]

**Comment by yu199195** [comment]
请描述的清楚一点，使用的什么版本，是如何上传的

**Comment by chyhub** [comment]
> 请描述的清楚一点，使用的什么版本，是如何上传的

分支用的master，通过jmeter上传的文件，走soul的http上传就直接报上面的错误，不走soul，直接访问controller可以上传成功

**Comment by yu199195** [comment]
请使用postman上传文件看看，我不知道你是怎么调用的
