### ISSUE TITLE
服务起来后简单配置了Divide过滤，报netty异常  java.io.IOException:

### ISSUE THREAD

**Issue by DvZhong** [Dromara/soul#24]
服务起来后简单配置了Divide过滤，网关基础功能可以实现，但是每次请求都会报一个netty异常， 找了好久没有找到什么原因引起的。

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_131]
	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[na:1.8.0_131]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[na:1.8.0_131]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[na:1.8.0_131]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[na:1.8.0_131]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-buffer-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108) ~[netty-buffer-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-common-4.1.29.Final.jar:4.1.29.Final]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_131]

**Comment by DvZhong** [comment]
> 什么分支，我这边并不会有这个错误

master 分支， 你用的是哪个分支？

**Comment by DvZhong** [comment]
> 什么分支，我这边并不会有这个错误

改到reslease分钟 也还会有这样错误，

2018-12-26 10:31:40.416 DEBUG 169472 --- [ctor-http-nio-2] o.d.soul.web.handler.SoulHandlerMapping  : [305637eb] Mapped to org.dromara.soul.web.handler.SoulWebHandler@a3bfde
2018-12-26 10:31:40.438 ERROR 169472 --- [ctor-http-nio-2] o.d.s.web.plugin.function.DividePlugin   : divide upstream config error：RuleZkDTO(id=ndEHt6JD, name=divide, selectorId=cJr9ZgR9, matchMode=0, sort=1, enabled=true, loged=false, handle={"requestVolumeThreshold":"20","errorThresholdPercentage":"50","maxConcurrentRequests":"100","sleepWindowInMilliseconds":"5000","groupKey":"","commandKey":"","loadBalance":"random","timeout":"20000","upstreamList":[{"upstreamHost":"127.0.0.1","protocol":"http://","upstreamUrl":"127.0.0.1:8901","timeout":"10000","retry":"0","weight":"1"}]}, conditionZkDTOList=[ConditionZkDTO(paramType=header, operator==, paramName=rpcType, paramValue=http)])
2018-12-26 10:31:40.524 ERROR 169472 --- [ctor-http-nio-2] reactor.netty.tcp.TcpServer              : [id: 0x305637eb, L:/127.0.0.1:8089 - R:/127.0.0.1:49783] onUncaughtException(SimpleConnection{channel=[id: 0x305637eb, L:/127.0.0.1:8089 - R:/127.0.0.1:49783]})

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_131]
	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[na:1.8.0_131]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[na:1.8.0_131]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[na:1.8.0_131]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[na:1.8.0_131]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-buffer-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108) ~[netty-buffer-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-common-4.1.29.Final.jar:4.1.29.Final]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_131]



我的配置:

server:
  port: 8089
  address: 0.0.0.0

spring:
   application:
    name: soul-bootstrap
   redis:
    password: 123456
    timeout: 300000ms
    sentinel:
          master: mymaster
          nodes:
              - 127.0.0.1:6379
   influxdb:
        url: http://localhost:8086
        username: test
        password: test
        database: test
        retention-policy: autogen
        connect-timeout: 10
        read-timeout: 30
        write-timeout: 10
   zookeeper:
        url : localhost:2181
        sessionTimeout: 5000
        connectionTimeout : 2000
        serializer : KryoSerializer
soul:
    bufferSize: 2048
    timeVerify:
       timeDelay : 10
       enabled: false
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: http://eureka.didispace.com/eureka/


logging:
    level:
        root: info
        org.springframework.boot: info
        org.apache.ibatis: info
        org.dromara.soul.bonuspoint: info
        org.dromara.soul.lottery: debug
        org.dromara.soul: debug

    path: "./logs/web"

**Comment by yu199195** [comment]
这么明显的提示了，你看下代码是哪一行？ 127.0.0.1:8901 能通？

**Comment by DvZhong** [comment]
> > 什么分支，我这边并不会有这个错误
> 
> master 分支， 你用的是哪个分支？

换到了realease分支还是有这个错误， 不知道是哪引起的。
2018-12-26 10:40:54.784 DEBUG 169564 --- [ctor-http-nio-3] o.d.soul.web.handler.SoulHandlerMapping  : [0a069ae4] Mapped to org.dromara.soul.web.handler.SoulWebHandler@587fa8a1
2018-12-26 10:40:57.740 ERROR 169564 --- [ctor-http-nio-3] reactor.netty.tcp.TcpServer              : [id: 0x0a069ae4, L:/127.0.0.1:8089 - R:/127.0.0.1:50709] onUncaughtException(SimpleConnection{channel=[id: 0x0a069ae4, L:/127.0.0.1:8089 - R:/127.0.0.1:50709]})

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_131]
	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[na:1.8.0_131]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[na:1.8.0_131]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[na:1.8.0_131]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[na:1.8.0_131]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-buffer-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108) ~[netty-buffer-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-common-4.1.29.Final.jar:4.1.29.Final]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_131]

我的配置:
server:
  port: 8089
  address: 0.0.0.0

spring:
   application:
    name: soul-bootstrap
   redis:
    password: 123456
    timeout: 300000ms
    sentinel:
          master: mymaster
          nodes:
              - 127.0.0.1:6379
   influxdb:
        url: http://localhost:8086
        username: test
        password: test
        database: test
        retention-policy: autogen
        connect-timeout: 10
        read-timeout: 30
        write-timeout: 10
   zookeeper:
        url : localhost:2181
        sessionTimeout: 5000
        connectionTimeout : 2000
        serializer : KryoSerializer
soul:
    bufferSize: 2048
    timeVerify:
       timeDelay : 10
       enabled: false
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: http://eureka.didispace.com/eureka/


logging:
    level:
        root: info
        org.springframework.boot: info
        org.apache.ibatis: info
        org.dromara.soul.bonuspoint: info
        org.dromara.soul.lottery: debug
        org.dromara.soul: debug

    path: "./logs/web"

**Comment by yu199195** [comment]
不要重复的贴，框架会有检查你url能否ping通的机制，如果不行了，就会有这个错误

**Comment by DvZhong** [comment]
> 这么明显的提示了，你看下代码是哪一行？ 127.0.0.1:8901 能通？

通的， 可以拿到返回信息，但是会有一个这个错误，
服务代码:

@RestController
public class UserController {
	
	@RequestMapping("/testHttp")
	public String testHttp() {
		return "你好我是小刚现在的时间是:"+new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
	}
}

**Comment by yu199195** [comment]
UrlUtils  类的checkUrl 打个断点看下

**Comment by DvZhong** [comment]
> UrlUtils 类的checkUrl 打个断点看下

checkUrl 是没有问题的。

每次请求后，在执行ResponsePlugin时报的这个错误。
