### ISSUE TITLE
2.2.0soul的client不兼容springboot1.5.x

### ISSUE THREAD

**Issue by java-Learner-lx** [Dromara/soul#256]
2.2.0soul+dubbo+springboot1.5.3,项目引入
`<dependency>
            <groupId>org.dromara</groupId>
            <artifactId>soul-spring-boot-starter-client-alibaba-dubbo</artifactId>
            <version>2.0.0</version>
        </dependency>`
但是报错
有小伙伴试过吗，求交流，求指导
2.1.2soul的client是没问题的

**Comment by yu199195** [comment]
什么错误

**Comment by java-Learner-lx** [comment]
2020-07-06 15:58:19.337 ERROR 1616 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.context.event.internalEventListenerProcessor': Initialization of bean failed; nested exception is java.lang.AbstractMethodError
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
	at cn.com.esgcc.gwtrip.MobileReimbServiceApplication.main(MobileReimbServiceApplication.java:27)
Caused by: java.lang.AbstractMethodError: null
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:423)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1633)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	... 13 common frames omitted

**Comment by yu199195** [comment]
你能自己解决吗

**Comment by java-Learner-lx** [comment]
> 你能自己解决吗

这个正在看（目前粗略定位在包冲突或者版本不兼容），可能有点难度，大佬。有小伙伴要是弄出来了，希望分享出来

**Comment by yu199195** [comment]
client代码就那么一点

**Comment by java-Learner-lx** [comment]
> client代码就那么一点

恩，我搂一遍

**Comment by java-Learner-lx** [comment]
大佬，我试了一下直接引
`<dependency>
            <groupId>org.dromara</groupId>
            <artifactId>soul-client-alibaba-dubbo</artifactId>
            <version>${project.version}</version>
        </dependency>`

为什么 不注册了呢，求大佬指点一下，我还在看 @yu199195

**Comment by yaochangbo** [comment]
解决了吗？同问

**Comment by java-Learner-lx** [comment]
> 解决了吗？同问

我在弄着，最近比较忙，你有时间也可以试试

**Comment by bomefile** [comment]
https://github.com/bomefile/soul-spring-boot-starter-client-springmvc 试试这个
