### ISSUE TITLE
spring-cloud-starter-openfeign 配合出现线程拒绝

### ISSUE THREAD

**Issue by hjjoe1213123** [dromara/soul#318]
Caused by: java.util.concurrent.RejectedExecutionException: Task org.dromara.soul.client.springcloud.init.SpringCloudClientBeanPostProcessor$$Lambda$568/660144865@2adc1e84 rejected from java.util.concurrent.ThreadPoolExecutor@2a99fa07[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063) ~[na:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830) ~[na:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379) ~[na:1.8.0_251]
	at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:668) ~[na:1.8.0_251]
	at org.dromara.soul.client.springcloud.init.SpringCloudClientBeanPostProcessor.postProcessBeforeInitialization(SpringCloudClientBeanPostProcessor.java:91) ~[soul-client-springcloud-2.2.0.jar:2.2.0]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:415) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	... 21 common frames omitted

**Comment by yu199195** [comment]
升级点2.2.1------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;辛末子午&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月28日(星期一) 晚上9:28
收件人:&nbsp;&quot;dromara/soul&quot;<soul@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[dromara/soul] spring-cloud-starter-openfeign 配合出现线程拒绝 (#318)

**Comment by hjjoe1213123** [comment]
确实版本问题，谢谢大佬
