### ISSUE TITLE
master添加用户报错

### ISSUE THREAD

**Issue by qq123zhz** [dromara/soul#398]
org.dromara.soul.common.exception.SoulException: org.dromara.soul.common.exception.SoulException: javax.crypto.IllegalBlockSizeException: Input length not multiple of 16 bytes
	at org.dromara.soul.admin.utils.CipherUtils.lambda$1(CipherUtils.java:143) ~[classes/:na]
	at java.util.Optional.map(Optional.java:215) ~[na:1.8.0_161]
	at org.dromara.soul.admin.utils.CipherUtils.decryptStr(CipherUtils.java:137) ~[classes/:na]
	at org.dromara.soul.admin.utils.AesUtils.aesDecryption(AesUtils.java:52) ~[classes/:na]
	at org.dromara.soul.admin.controller.DashboardUserController.lambda$0(DashboardUserController.java:77) ~[classes/:na]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_161]
	at org.dromara.soul.admin.controller.DashboardUserController.queryDashboardUsers(DashboardUserController.java:76) ~[classes/:na]
	at sun.reflect.GeneratedMethodAccessor190.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]

**Comment by nuo-promise** [comment]
> org.dromara.soul.common.exception.SoulException: org.dromara.soul.common.exception.SoulException: javax.crypto.IllegalBlockSizeException: Input length not multiple of 16 bytes
> at org.dromara.soul.admin.utils.CipherUtils.lambda$1(CipherUtils.java:143) ~[classes/:na]
> at java.util.Optional.map(Optional.java:215) ~[na:1.8.0_161]
> at org.dromara.soul.admin.utils.CipherUtils.decryptStr(CipherUtils.java:137) ~[classes/:na]
> at org.dromara.soul.admin.utils.AesUtils.aesDecryption(AesUtils.java:52) ~[classes/:na]
> at org.dromara.soul.admin.controller.DashboardUserController.lambda$0(DashboardUserController.java:77) ~[classes/:na]
> at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_161]
> at org.dromara.soul.admin.controller.DashboardUserController.queryDashboardUsers(DashboardUserController.java:76) ~[classes/:na]
> at sun.reflect.GeneratedMethodAccessor190.invoke(Unknown Source) ~[na:na]
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]

 我看下

**Comment by nuo-promise** [comment]
> org.dromara.soul.common.exception.SoulException: org.dromara.soul.common.exception.SoulException: javax.crypto.IllegalBlockSizeException: Input length not multiple of 16 bytes
> at org.dromara.soul.admin.utils.CipherUtils.lambda$1(CipherUtils.java:143) ~[classes/:na]
> at java.util.Optional.map(Optional.java:215) ~[na:1.8.0_161]
> at org.dromara.soul.admin.utils.CipherUtils.decryptStr(CipherUtils.java:137) ~[classes/:na]
> at org.dromara.soul.admin.utils.AesUtils.aesDecryption(AesUtils.java:52) ~[classes/:na]
> at org.dromara.soul.admin.controller.DashboardUserController.lambda$0(DashboardUserController.java:77) ~[classes/:na]
> at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_161]
> at org.dromara.soul.admin.controller.DashboardUserController.queryDashboardUsers(DashboardUserController.java:76) ~[classes/:na]
> at sun.reflect.GeneratedMethodAccessor190.invoke(Unknown Source) ~[na:na]
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]

新增用户时候 报的错误么？
