### ISSUE TITLE
ApacheDubboServiceBeanPostProcessor初始化Dubbo元数据失败

### ISSUE THREAD

**Issue by KevinClair** [dromara/soul#415]
## Describe the bug
客户端通过@SoulDubboClient上传到Admin控制台上去的服务，由于调用/soul-client/dubbo-register方法在dubbo正式暴露服务之前，所以bootstrap的ApplicationConfigCache的build服务在做get时，会提示Dubbo no provider的错误。
```java
public ReferenceConfig<GenericService> build(final MetaData metaData) {
        ReferenceConfig<GenericService> reference = new ReferenceConfig<>();
        reference.setGeneric(true);
        reference.setApplication(applicationConfig);
        reference.setRegistry(registryConfig);
        reference.setInterface(metaData.getServiceName());
        reference.setProtocol("dubbo");
        String rpcExt = metaData.getRpcExt();
        DubboParamExtInfo dubboParamExtInfo = GsonUtils.getInstance().fromJson(rpcExt, DubboParamExtInfo.class);
        if (Objects.nonNull(dubboParamExtInfo)) {
            if (StringUtils.isNoneBlank(dubboParamExtInfo.getVersion())) {
                reference.setVersion(dubboParamExtInfo.getVersion());
            }
            if (StringUtils.isNoneBlank(dubboParamExtInfo.getGroup())) {
                reference.setGroup(dubboParamExtInfo.getGroup());
            }
            if (StringUtils.isNoneBlank(dubboParamExtInfo.getLoadbalance())) {
                final String loadBalance = dubboParamExtInfo.getLoadbalance();
                reference.setLoadbalance(buildLoadBalanceName(loadBalance));
            }
            if (StringUtils.isNoneBlank(dubboParamExtInfo.getUrl())) {
                reference.setUrl(dubboParamExtInfo.getUrl());
            }
            Optional.ofNullable(dubboParamExtInfo.getTimeout()).ifPresent(reference::setTimeout);
            Optional.ofNullable(dubboParamExtInfo.getRetries()).ifPresent(reference::setRetries);
        }
        // 此时dubbo服务还未正式暴露出去，这里get会出现no provider的异常错误。
        Object obj = reference.get();
        if (obj != null) {
            log.info("init apache dubbo reference success there meteData is :{}", metaData.toString());
            cache.put(metaData.getPath(), reference);
        }
        return reference;
    }
```
## Environment

- Soul version(s): [e.g. 2.2.1]

## Steps to reproduce
* 具体表现为：
    * 启动Admin;
    * 启动Bootstrap(此时Dubbo元数据已经存在于元数据列表);
    * 启动Application(应用);
    * 应用启动成功，dubbo服务注册成功，但是Bootstrap此时抛出Dubbo no provider异常。

## Expected behavior
* Bootstrap正常获取到服务列表，更新本地缓存；
* 本地已修复，需要的话可以提交pull request.

## Debug logs
<details>
<summary>Click to expand</summary>

```
java.lang.IllegalStateException: Failed to check the status of the service com.*.TestService. No provider available for the service com.*.TestService:1.1.0
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:350) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:258) ~[dubbo-2.7.7.jar:2.7.7]
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:158) ~[dubbo-2.7.7.jar:2.7.7]
	at org.dromara.soul.plugin.apache.dubbo.cache.ApplicationConfigCache.build(ApplicationConfigCache.java:173) ~[classes/:na]
	at org.dromara.soul.plugin.apache.dubbo.cache.ApplicationConfigCache.initRef(ApplicationConfigCache.java:137) ~[classes/:na]
	at org.dromara.soul.plugin.apache.dubbo.subscriber.ApacheDubboMetaDataSubscriber.onSubscribe(ApacheDubboMetaDataSubscriber.java:44) ~[classes/:na]
	at org.dromara.soul.plugin.sync.data.weboscket.handler.MetaDataHandler.lambda$null$2(MetaDataHandler.java:47) ~[classes/:na]
	at java.util.ArrayList.forEach(ArrayList.java:1255) ~[na:1.8.0_151]
	at org.dromara.soul.plugin.sync.data.weboscket.handler.MetaDataHandler.lambda$doUpdate$3(MetaDataHandler.java:47) ~[classes/:na]
	at java.util.ArrayList.forEach(ArrayList.java:1255) ~[na:1.8.0_151]
	at org.dromara.soul.plugin.sync.data.weboscket.handler.MetaDataHandler.doUpdate(MetaDataHandler.java:47) ~[classes/:na]
	at org.dromara.soul.plugin.sync.data.weboscket.handler.AbstractDataHandler.handle(AbstractDataHandler.java:72) ~[classes/:na]
	at org.dromara.soul.plugin.sync.data.weboscket.handler.WebsocketDataHandler.executor(WebsocketDataHandler.java:61) ~[classes/:na]
	at org.dromara.soul.plugin.sync.data.weboscket.client.SoulWebsocketClient.handleResult(SoulWebsocketClient.java:87) ~[classes/:na]
	at org.dromara.soul.plugin.sync.data.weboscket.client.SoulWebsocketClient.onMessage(SoulWebsocketClient.java:68) ~[classes/:na]
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:591) [Java-WebSocket-1.5.0.jar:na]
	at org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:885) [Java-WebSocket-1.5.0.jar:na]
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:819) [Java-WebSocket-1.5.0.jar:na]
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:379) [Java-WebSocket-1.5.0.jar:na]
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:216) [Java-WebSocket-1.5.0.jar:na]
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:508) [Java-WebSocket-1.5.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
```
</details>

**Comment by yu199195** [comment]
不是之前改了吗

**Comment by KevinClair** [comment]
> 不是之前改了吗

不是一个问题，之前的问题是Dubbo元数据上传到Admin那里，对于同样的path的元数据没有做更新，返回了path has exist，这个上次提交改了。这个问题其实以前一直存在，我以为是自己操作不当，这两天研究了一下，觉得是上传的顺序跟dubbo暴露的顺序问题导致的。

**Comment by yu199195** [comment]
ok,pr 上来吧， 客户端那调整吧

**Comment by KevinClair** [comment]
> ok,pr 上来吧， 客户端那调整吧

是的，需要那边调整一下顺序。

**Comment by dengliming** [comment]
@KevinClair 这个是解决了的对吧

**Comment by KevinClair** [comment]
嗯，已修复。
