### ISSUE TITLE
规则配置超时时间必填bug

### ISSUE THREAD

**Issue by liyong1028826685** [Dromara/soul#47]
<img width="789" alt="image" src="https://user-images.githubusercontent.com/6101259/56860399-dc2fb300-69c8-11e9-8458-665a5ff9f436.png">

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/6101259/56860413-008b8f80-69c9-11e9-8e99-73bbea3ff393.png">

Caused by: java.lang.NumberFormatException: empty String
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1193)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:243)

**Comment by yu199195** [comment]
这里必须填的，前期这么没有验证
