### ISSUE TITLE
soul-bootstrap NPE Exception

### ISSUE THREAD

**Issue by nuo-promise** [dromara/soul#846]
## Describe the bug

If the Rule has data, and the Selector has no corresponding data, soul-Admin will return null, and it will also pass to Soul-bootstrap, followed by the NPE when the JSON String passes to the Object
## Environment

- Soul version(s): [e.g. 2.2.1]
2.2.1
## Steps to reproduce
1. start soul-admin
2. start soul-bootstrap

## Debug logs

`java.lang.NullPointerException: null
	at org.dromara.soul.plugin.base.cache.BaseDataCache.removeRuleData(BaseDataCache.java:187) ~[classes/:na]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_191]
	at org.dromara.soul.plugin.base.cache.BaseDataCache.cleanRuleDataSelf(BaseDataCache.java:204) ~[classes/:na]
	at org.dromara.soul.plugin.base.cache.CommonPluginDataSubscriber.refreshRuleDataSelf(CommonPluginDataSubscriber.java:121) ~[classes/:na]
	at org.dromara.soul.plugin.sync.data.weboscket.handler.RuleDataHandler.doRefresh(RuleDataHandler.java:41) ~[classes/:na]
	at org.dromara.soul.plugin.sync.data.weboscket.handler.AbstractDataHandler.handle(AbstractDataHandler.java:68) ~[classes/:na]
	at org.dromara.soul.plugin.sync.data.weboscket.handler.WebsocketDataHandler.executor(WebsocketDataHandler.java:61) ~[classes/:na]
	at org.dromara.soul.plugin.sync.data.weboscket.client.SoulWebsocketClient.handleResult(SoulWebsocketClient.java:87) ~[classes/:na]
	at org.dromara.soul.plugin.sync.data.weboscket.client.SoulWebsocketClient.onMessage(SoulWebsocketClient.java:68) ~[classes/:na]
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:591) [Java-WebSocket-1.5.0.jar:na]
	at org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:885) [Java-WebSocket-1.5.0.jar:na]
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:819) [Java-WebSocket-1.5.0.jar:na]
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:379) [Java-WebSocket-1.5.0.jar:na]
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:216) [Java-WebSocket-1.5.0.jar:na]
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:508) [Java-WebSocket-1.5.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
`
<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by nuo-promise** [comment]
Fix tomorrow @dengliming

**Comment by nuo-promise** [comment]
Please Review @yu199195 @dengliming
